import os
import sys

print("""
╔══════════════════════════════════════════════════════╗
║     🐇 Rabbitt AI — Sales Insight Automator          ║
║            Interactive Setup Wizard                  ║
╚══════════════════════════════════════════════════════╝
""")

print("This will create your .env file. Press Enter to skip optional fields.\n")

# ── Gemini ──────────────────────────────────────────────────
print("─" * 54)
print("STEP 1 — Google Gemini API Key")
print("Get it free at: https://aistudio.google.com/app/apikey")
print("─" * 54)
gemini_key = input("Paste your Gemini API key: ").strip()
while not gemini_key:
    print("⚠  Gemini key is required.")
    gemini_key = input("Paste your Gemini API key: ").strip()

# ── Gmail ────────────────────────────────────────────────────
print()
print("─" * 54)
print("STEP 2 — Gmail Address (for sending reports)")
print("─" * 54)
smtp_user = input("Your Gmail address: ").strip()
while "@" not in smtp_user:
    print("⚠  Enter a valid email address.")
    smtp_user = input("Your Gmail address: ").strip()

print()
print("─" * 54)
print("STEP 3 — Gmail App Password")
print("Get it at: https://myaccount.google.com/apppasswords")
print("Type any name → click Create → copy the 16 chars")
print("─" * 54)
smtp_pass = input("Paste App Password (no spaces): ").strip().replace(" ", "")
while len(smtp_pass) < 16:
    print("⚠  App Password should be 16 characters. Try again.")
    smtp_pass = input("Paste App Password (no spaces): ").strip().replace(" ", "")

# ── Sender name ──────────────────────────────────────────────
print()
print("─" * 54)
print("STEP 4 — Sender Display Name (optional)")
print("─" * 54)
sender_name = input("Sender name [Rabbitt AI Sales Insights]: ").strip()
if not sender_name:
    sender_name = "Rabbitt AI Sales Insights"

# ── API Key ──────────────────────────────────────────────────
print()
print("─" * 54)
print("STEP 5 — App API Key (protects your backend)")
print("This is a password YOU choose — anything works.")
print("─" * 54)
api_key = input("Choose an API key [rabbitt-dev-key-change-in-prod]: ").strip()
if not api_key:
    api_key = "rabbitt-dev-key-change-in-prod"

# ── Write .env ───────────────────────────────────────────────
env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")

env_content = f"""# Auto-generated by setup.py - DO NOT COMMIT THIS FILE

# AI Engine
GEMINI_API_KEY={gemini_key}

# Email Delivery
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER={smtp_user}
SMTP_PASS={smtp_pass}
SENDER_NAME={sender_name}

# Security
APP_API_KEY={api_key}

# CORS
ALLOWED_ORIGINS=http://localhost,http://localhost:3000,http://127.0.0.1:3000

# Upload
MAX_FILE_SIZE_MB=10
"""

with open(env_path, "w", encoding="utf-8") as f:
    f.write(env_content)

print(f"""
╔══════════════════════════════════════════════════════╗
║              ✅  .env file created!                  ║
╚══════════════════════════════════════════════════════╝

  File saved to: {env_path}

  GEMINI_API_KEY  → {'✅ set' if gemini_key else '❌ missing'}
  SMTP_USER       → {smtp_user}
  SMTP_PASS       → {'*' * len(smtp_pass)} ({len(smtp_pass)} chars)
  SENDER_NAME     → {sender_name}
  APP_API_KEY     → {api_key}

  Next step — come back to the other window and
  tell me when pip install finishes!
""")
